### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by emma994** [Riverscapes/gcd#300] opened 2018-07-30 09:09 UTC
After adding the raster I get this error message:

Attempted to divide by zero.
 --- Stacktrace --- 
   at System.Decimal.FCallDivide(Decimal& d1, Decimal& d2)
   at GCDConsoleLib.ExtentRectangle.GetDivisibleExtent() in D:\Code\gcd\gcd\GCDConsoleLib\ExtentRectangle.cs:line 376
   at GCDCore.UserInterface.SurveyLibrary.ExtentImporter.Initialize(Decimal cellWidth)
   at GCDCore.UserInterface.SurveyLibrary.ExtentImporter.set_InputExtent(ExtentRectangle value)
   at GCDCore.UserInterface.SurveyLibrary.frmImportRaster.OnRasterChanged(Object sender, PathEventArgs e)
 --- Exception Data --- 
ArcMap = 10.5.1.7333
GCD = 7.1.1.0
Windows: Microsoft Windows NT 6.2.9200.0
Date: 30/07/2018 10:08:13

**Comment by philipbaileynar** [comment] 2018-08-02 20:29
Hi @emma994 can you please zip and send one of your rasters please? 

Respond and let me know if it's too big or you don't have a means of sending it and I can help out.

**Comment by emma994** [comment] 2018-08-07 07:55
Hi Philip,
I cannot share the files as they are too big. Would you be willing to share your email address with me and I can send you a link to onedrive to access it.
Thanks,
Emma

**Comment by philipbaileynar** [comment] 2018-08-07 17:33
Hi Emma,

Info@northarrowresearch.com

**Comment by emma994** [comment] 2018-08-08 13:44
Thanks Philip, I have granted you access to the one drive. Let me know if you cannot access it.

**Comment by philipbaileynar** [comment] 2018-08-22 18:41
Hi @emma994 I just tried downloading the file and OneDrive/SharePoint won't let me because it is larger than 25Mb. Do you have another way of getting this to me please?

**Comment by philipbaileynar** [comment] 2018-08-22 19:09
@emma994 found a way to get it!

The problem is related to the fact that the data are unprojected and stored in decimal degrees. We are working on a proper warning message instead of a hard error, but we recommend that you reproject into a non-geopgrahic projection such as the British National Grid or Universal Transverse Meractor.

GCD requires projected data that is represented using linear units, as opposed to angular units, so that it can calculate accurate areas and volumes.

**Comment by philipbaileynar** [comment] 2018-08-22 19:58
Not withstanding that GCD should not be used with angular coordinates, the fix for this error so that GCD does not crash with very small cell widths will be part of the next GCD release. Closing this issue.

**Closed by philipbaileynar** 2018-08-22 19:58 UTC
